In [1]:
!python DeePred-BBB_Script.py

Processing SCC(=O)[C@@]1(O)[C@@]2(C)[C@H]([C@H]3[C@H]([C@H](O)C2)[C@]2(C)C(=CC(=O)CC2)CC3)CC1 in smiles.smi (1/3605).
Processing s1cc(nc1[NH]=C(N)N)C in smiles.smi (2/3605).
Processing s1cc(CSCCNC(NC)=[NH]C#N)nc1[NH]=C(N)N in smiles.smi (3/3605).
Processing s1c(ncc1)CCN in smiles.smi (4/3605).
Processing S=P(N1CC1)(N2CC2)N3CC3 in smiles.smi (5/3605).
Processing S=C2NCCC(COc1ccccc1)O2 in smiles.smi (6/3605).
Processing S=C1O[C@@H](COc2ccccc2)CCN1 in smiles.smi (7/3605).
Processing S=C1NC(=O)C(CC=C)([C@H]2C=CCCC2)C(=O)N1 in smiles.smi (8/3605).
Processing S=C1NC(=O)C([C@@H](CCC)CC)(CC)C(=O)N1 in smiles.smi (9/3605). Average speed: 1.53 s/mol.
Processing S=C1NC(=O)C([C@@H](CCC)C)(CC=C)C(=O)N1 in smiles.smi (10/3605). Average speed: 1.54 s/mol.
Processing S=C1NC(=O)C([C@@H](CCC)C)(CC)C(=O)N1 in smiles.smi (11/3605). Average speed: 0.64 s/mol.
Processing S(SC[C@H]1OCCC1)/C(=C(/N(C=O)Cc1c(N)nc(C)nc1)\C)/CCO in smiles.smi (13/3605). Average speed: 0.40 s/mol.
Processing S=C1N(CC=C)C(=O)[C@H](CC(C)C)N1 in smiles.smi (12/3605). Average speed: 0.50 s/mol.
Processing S(S/C(=C(/N(C=O)Cc1c(N)nc(C)nc1)\C)/CCOC(=O)c1ccccc1)/C(=C(/N(C=O)Cc1c(N)nc(C)nc1)\C)/CCOC(=O)c1ccccc1 in smiles.smi (14/3605). Average speed: 0.41 s/mol.
Processing S(CCNC1=NCC(Cc2cnc(C)cc2)=CN1)Cc1oc(CN(C)C)cc1 in smiles.smi (16/3605). Average speed: 0.28 s/mol.
Processing S(CCNCNC)Cc1c(C)[nH]cn1.N#CN in smiles.smi (15/3605). Average speed: 0.32 s/mol.
Processing S(CCNC=N)C1=C(C(=O)O)N2C(=O)[C@H]([C@H](O)C)[C@H]2C1 in smiles.smi (17/3605). Average speed: 0.26 s/mol.
Processing S(CCN[C@H](NC#N)NC)Cc1nc(N[C-]([N+H3])N)sc1 in smiles.smi (18/3605). Average speed: 0.23 s/mol.
Processing S(CCN[C@@H](NC)C[N+](=O)[O-])Cc1oc(CN(C)C)cc1 in smiles.smi (19/3605). Average speed: 0.22 s/mol.
Processing S(CCN[C@@H](NC#N)NC)Cc1nc(N[C-]([N+H3])N)sc1 in smiles.smi (20/3605). Average speed: 0.21 s/mol.
Processing S(CCC1([C@H](CCC)C)C(=O)NC(=S)NC1=O)C in smiles.smi (21/3605). Average speed: 0.21 s/mol.
Processing S(CC1=C(C(=O)OCC2=C(C)OC(=O)O2)N2C(=O)[C@@H](NC(=O)[C@H](OC(=O)[C@@H](N)C)c3ccccc3)[C@H]2SC1)c1sc(C)nn1 in smiles.smi (22/3605). Average speed: 0.20 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@H](NC(=O)Cn3nnnc3)[C@@H]2SC1)c1sc(C)nn1 in smiles.smi (23/3605). Average speed: 0.19 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@H](NC(=O)[C@H](O)c3ccccc3)[C@H]2SC1)c1n(C)nnn1 in smiles.smi (24/3605). Average speed: 0.18 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@H](NC(=O)[C@@H](NC(=O)N3C(=O)C(=O)N(CC)CC3)c3ccc(O)cc3)[C@H]2SC1)c1n(C)nnn1 in smiles.smi (25/3605). Average speed: 0.17 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@H](NC(=O)[C@@H](N)c3ccc(O)cc3)[C@@H]2SC1)c1sc(C)nn1 in smiles.smi (26/3605). Average speed: 0.17 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@H](NC(=O)/C(=N/OC)/c3nc(N)sc3)[C@H]2SC1)c1sc(CC(=O)O)c(C)n1 in smiles.smi (27/3605). Average speed: 0.17 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@H](NC(=O)/C(=N/OC)/c3nc(N)sc3)[C@H]2SC1)c1n(C)nnn1 in smiles.smi (28/3605). Average speed: 0.17 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@H](NC(=O)/C(=N/OC)/c3nc(N)sc3)[C@H]2SC1)C=1N(C)NC(=O)C(=O)N=1 in smiles.smi (29/3605). Average speed: 0.19 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@H](NC(=O)/C(=N/OC)/c3nc(N)sc3)[C@@H]2SC1)c1snnc1 in smiles.smi (30/3605). Average speed: 0.20 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@](OC)(NC(=O)C3S/C(=C(/C(=O)O)\C#N)/S3)[C@H]2SC1)c1n(C)nnn1 in smiles.smi (31/3605). Average speed: 0.19 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@@H](NC(=O)Cn3nnnc3)[C@@H]2SC1)c1scnn1 in smiles.smi (32/3605). Average speed: 0.21 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@@H](NC(=O)Cc3sccc3)[C@@H]2SC1)C1=NCNN1 in smiles.smi (33/3605). Average speed: 0.20 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@@H](NC(=O)Cc3nc(N)sc3)[C@@H]2SC1)c1n(CCN(C)C)nnn1 in smiles.smi (34/3605). Average speed: 0.21 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@@H](NC(=O)Cc3c(CN)cccc3)[C@@H]2SC1)c1n(CC(=O)O)nnn1 in smiles.smi (35/3605). Average speed: 0.21 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@@H](NC(=O)[C@H](NC(=O)c3c(O)cc(C)nc3)c3ccc(O)cc3)[C@@H]2SC1)c1n(C)nnn1 in smiles.smi (36/3605). Average speed: 0.21 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@@H](NC(=O)[C@H](N)c3ccc(O)cc3)[C@@H]2SC1)c1nn[nH]c1 in smiles.smi (37/3605). Average speed: 0.20 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@@H](NC(=O)[C@@H](O)c3ccccc3)[C@H]2SC1)c1sc(C)nn1 in smiles.smi (38/3605). Average speed: 0.20 s/mol.
Processing S(CC1=C(C(=O)O)N2C(=O)[C@@](OC)(NC(=O)[C@@H](C(=O)O)c3ccc(O)cc3)[C@@H]2OC1)c1n(C)nnn1 in smiles.smi (39/3605). Average speed: 0.19 s/mol.
Processing S(CC[C@@H](NC(=O)C)C(=O)Oc1ccc(NC(=O)C)cc1)C in smiles.smi (40/3605). Average speed: 0.20 s/mol.
Processing S(CC)[C@]1(SC)[C@@]2(C)[C@@H]([C@@H]3[C@@](F)([C@@H](O)C2)[C@@]2(C)C(=CC(=O)C=C2)CC3)CC1 in smiles.smi (41/3605). Average speed: 0.20 s/mol.
Processing S(CC(=O)N[C@H]1C(=O)N2[C@H](C(=O)O)C(C)(C)S[C@H]12)c1ccccc1 in smiles.smi (42/3605). Average speed: 0.20 s/mol.
Processing S(CC(=O)N[C@@H]1C(=O)N2C(C(=O)O)=C(COC(=O)C)CS[C@H]12)c1ccncc1 in smiles.smi (43/3605). Average speed: 0.19 s/mol.
Processing S(C[C@H]1CN(CCC)[C@H]2[C@@H](c3c4c([nH]cc4C2)ccc3)C1)C in smiles.smi (46/3605). Average speed: 0.19 s/mol.
Processing S(CC#N)CC(=O)N[C@]1(OC)C(=O)N2C(C(=O)O)=C(CSc3n(C)nnn3)CS[C@@H]12 in smiles.smi (45/3605). Average speed: 0.19 s/mol.
Processing S(CC(=O)N[C@@H]1C(=O)N2[C@H](C(=O)O)C(C)(C)S[C@@H]12)CC=C in smiles.smi (44/3605). Average speed: 0.19 s/mol.
Processing S(C[C@H](NC(=O)c1c(C)c(O)ccc1)[C@H](O)CN1[C@H](C(=O)NC(C)C)C[C@H]2[C@@H](C1)CCCC2)c1ccccc1 in smiles.smi (47/3605). Average speed: 0.19 s/mol.
Processing S(C[C@H](N)C(=O)O)CC(=O)N[C@@]1(OC)C(=O)N2C(C(=O)O)=C(CSc3n(C)nnn3)CS[C@H]12 in smiles.smi (48/3605). Average speed: 0.18 s/mol.
Processing S(C[C@@H]1C=C2[C@@H](N(C)C1)Cc1c3c([nH]c1)cccc23)c1ncccc1 in smiles.smi (49/3605). Average speed: 0.18 s/mol.
Processing S(C[C@@H](NC(=O)c1c(C)c(O)ccc1)[C@@H](O)CN1[C@@H](C(=O)NC(C)(C)C)C[C@@H]2[C@@H](C1)CCCC2)c1ccccc1 in smiles.smi (50/3605). Average speed: 0.18 s/mol.
Processing S(C)c1ccc(CC(=O)N2[C@@H](CN3C[C@H](O)CC3)CN(C(=O)C)CC2)cc1 in smiles.smi (51/3605). Average speed: 0.18 s/mol.
Processing S(C)c1cc2N(CC[C@H]3N(C)CCCC3)c3c(Sc2cc1)cccc3 in smiles.smi (53/3605). Average speed: 0.18 s/mol.
Processing S(C)c1cc2N(CC[C@H]3NCCCC3)c3c(Sc2cc1)cccc3 in smiles.smi (52/3605). Average speed: 0.18 s/mol.
Processing S(C)c1cc2N(C[C@H](CN(C)C)C)c3c(Sc2cc1)cccc3 in smiles.smi (54/3605). Average speed: 0.18 s/mol.
Processing S(C)c1cc2[C@@H](N3CCN(C)CC3)Cc3c(Sc2cc1)cccc3 in smiles.smi (55/3605). Average speed: 0.18 s/mol.
Processing S(C)[C@H]1[C@@H](O)[C@H](O)[C@@H](O)[C@H]([C@H](NC(=O)[C@@H]2N(C)C[C@@H](CCC)C2)[C@@H](O)C)O1 in smiles.smi (56/3605). Average speed: 0.17 s/mol.
Processing S(C(F)(F)F)CC(=O)N[C@@H]1C(=O)N2C(C(=O)O)=C(CSc3n(C)nnn3)CS[C@@H]12 in smiles.smi (58/3605). Average speed: 0.18 s/mol.
Processing S(C(F)F)CC(=O)N[C@]1(OC)C(=O)N2C(C(=O)O)=C(CSc3n(CCO)nnn3)CO[C@@H]12 in smiles.smi (57/3605). Average speed: 0.18 s/mol.
Processing S(C(CNc1c([N+](=O)[O-])cc[nH]1)(C)C)C(C)(C)c1nc(C)c(C)c(C)c1 in smiles.smi (59/3605). Average speed: 0.17 s/mol.
Processing S(C(=O)OCC)/C(=C(/N(C=O)Cc1c(N)nc(C)nc1)\C)/CCOC(=O)OCC in smiles.smi (60/3605). Average speed: 0.17 s/mol.
Processing S(C(=O)c1occc1)CC1=C(C(=O)O)N2C(=O)[C@H](NC(=O)/C(=N/OC)/c3nc(N)sc3)[C@H]2SC1 in smiles.smi (61/3605). Average speed: 0.17 s/mol.
Processing S(C(=O)C)C[C@H](C(=O)NCC(=O)OCc1ccccc1)Cc1ccccc1 in smiles.smi (62/3605). Average speed: 0.17 s/mol.
Processing S(C(=O)C(C)(C)C)CC(=O)[C@@]1(O)[C@@]2(C)[C@H]([C@H]3[C@H]([C@@H](O)C2)[C@@]2(C)C(=CC(=O)CC2)CC3)CC1 in smiles.smi (63/3605). Average speed: 0.17 s/mol.
Processing S(C(=O)[C@]1(OC(=O)CC)[C@@H](C)C[C@H]2[C@@]1(C)C[C@H](O)[C@@]1(F)[C@@]3(C)C([C@H](F)C[C@H]21)=CC(=O)C=C3)CF in smiles.smi (64/3605). Average speed: 0.16 s/mol.
Processing S(C(=O)[C@]1(OC(=O)CC)[C@@H](C)C[C@H]2[C@@]1(C)C[C@H](O)[C@@]1(F)[C@@]3(C)C([C@H](F)C[C@H]21)=CC(=O)C=C3)C in smiles.smi (65/3605). Average speed: 0.16 s/mol.
Processing S(C(=O)[C@]1(OC(=O)C)[C@@H](C)C[C@H]2[C@@]1(C)C[C@H](O)[C@@]1(F)[C@@]3(C)C(=CC(=O)C=C3)CC[C@H]21)C in smiles.smi (66/3605). Average speed: 0.16 s/mol.
Processing S(C(=O)[C@]1(O)[C@H](C)C[C@H]2[C@@]1(C)C[C@H](O)[C@@]1(F)[C@@]3(C)C([C@H](F)C[C@H]21)=CC(=O)C=C3)CF in smiles.smi (67/3605). Average speed: 0.16 s/mol.
Processing S(C(=O)[C@@]1(O)[C@@H](C)C[C@@H]2[C@]1(C)C[C@@H](O)[C@]1(F)[C@]3(C)C(=CC(=O)C=C3)CC[C@@H]21)C in smiles.smi (68/3605). Average speed: 0.16 s/mol.
Processing S(=O)(=O)(ON1C(=O)[C@@H](NC/C(=N\OCC(=O)O)/c2nc(N)sc2)C1(C)C)O in smiles.smi (69/3605). Average speed: 0.16 s/mol.
Processing S(=O)(=O)(OC[C@]12OC(C)(C)O[C@@H]1[C@H]1OC(C)(C)O[C@H]1CO2)N in smiles.smi (70/3605). Average speed: 0.16 s/mol.
Processing S(=O)(=O)(O)N1[C@H](C)[C@H](NC(=O)/C(=N\OC(C(=O)O)(C)C)/c2nc(N)sc2)C1=O in smiles.smi (71/3605). Average speed: 0.16 s/mol.
Processing S(=O)(=O)(O)N1[C@@H](COC(=O)N)[C@@H](NC(=O)/C(=N\OCC(=O)O)/c2nc(N)sc2)C1=O in smiles.smi (72/3605). Average speed: 0.16 s/mol.
Processing S(=O)(=O)(O)N[C@@H](C(=O)N[C@H]1C(=O)N2[C@@H](C(=O)O)C(C)(C)S[C@@H]12)c1ccccc1 in smiles.smi (73/3605). Average speed: 0.16 s/mol.
Processing S(=O)(=O)(O)Cn1c(SCC2=C(C(=O)O)N3C(=O)[C@@H](NC(=O)[C@@H](O)c4ccccc4)[C@H]3SC2)nnn1 in smiles.smi (74/3605). Average speed: 0.16 s/mol.
Processing S(=O)(=O)(O)CCC1C=CN(CC2=C(C(=O)O)N3C(=O)[C@@H](NC(=O)[C@H](NC(=O)c4c(C(=O)O)[nH]cn4)c4ccccc4)[C@@H]3SC2)C=C1 in smiles.smi (75/3605). Average speed: 0.16 s/mol.
Processing S(=O)(=O)(O)CCC[N+]1([C-H2])[C@@H]2CC(OC(=O)[C@@H](CO)c3ccccc3)C[C@@H]1CC2 in smiles.smi (76/3605). Average speed: 0.16 s/mol.
Processing S(=O)(=O)(O)c1cc(C(=O)OCC(=O)[C@]2(O)[C@H](C)C[C@@H]3[C@@]2(C)C[C@H](O)[C@H]2[C@@]4(C)C(C(C)=C[C@@H]32)=Cc2n(-c3ccccc3)ncc2C4)ccc1 in smiles.smi (77/3605). Average speed: 0.16 s/mol.
Processing S(=O)(=O)(O)[C@H](C(=O)N[C@H]1C(=O)N2[C@@H](C(=O)O)[C@@H](CN3C=CC(C(=O)N)C=C3)CS[C@H]12)c1ccccc1 in smiles.smi (78/3605). Average speed: 0.16 s/mol.
Processing S(=O)(=O)(Nc1ccc([C@H](O)CNC(C)C)cc1)C in smiles.smi (80/3605). Average speed: 0.16 s/mol.
Processing S(=O)(=O)(O)[C@@H](C(=O)N[C@@H]1C(=O)N2[C@H](C(=O)O)C(C)(C)S[C@H]12)c1ccccc1 in smiles.smi (79/3605). Average speed: 0.16 s/mol.
Processing S(=O)(=O)(Nc1cc([C@@H](N)C(=O)N[C@@H]2C(=O)N3C(C(=O)O)=C(C)CS[C@@H]23)ccc1)C in smiles.smi (81/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(NC)c1c(N)cc(OC)c(C(=O)NC[C@H]2N(CC=C)CCC2)c1 in smiles.smi (82/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(N[C@H](N)CCSCc1nc(N[C-]([N+H3])N)sc1)N in smiles.smi (83/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(N)c1ccc(Nc2nc(O)c(NC(=O)N[C@H](C(=O)N[C@H]3C(=O)N4[C@H](C(=O)O)C(C)(C)S[C@@H]34)c3ccc(O)cc3)cn2)cc1 in smiles.smi (84/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(N)c1cc(OC)c(OC)c(C(=O)NC[C@@H]2N(CC=C)CCC2)c1 in smiles.smi (85/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(N)c1cc(C(=O)NC[C@H]2N(CCC)CCC2)c(OC)cc1 in smiles.smi (86/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(N)c1cc(C(=O)NC[C@H]2N(CC)CCC2)c(OC)cc1 in smiles.smi (87/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(N)c1cc(C(=O)NC[C@@H]2N(Cc3ccc(F)cc3)CCC2)c(OC)cc1 in smiles.smi (88/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(N)c1cc(C(=O)NC[C@@H]2N(C)CCC2)c(OC)cc1 in smiles.smi (89/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(N(CCO)CCO)c1ccc(C=2NC(=O)C(C(=O)N[C@@H](C(=O)N[C@H]3C(=O)N4[C@@H](C(=O)O)C(C)(C)S[C@H]34)c3ccc(O)cc3)=CC=2)cc1 in smiles.smi (90/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(N(CC)CC)N[C@H]1CN(CCC)[C@@H]2[C@H](C1)Cc1c(O)cccc1C2 in smiles.smi (91/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(N(CC)CC)N[C@H]1CN(C)[C@@H]2[C@@H](c3c4c([nH]cc4C2)ccc3)C1 in smiles.smi (92/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(N(C)C)N[C@H]1CN(C)[C@H]2[C@@H](c3c4c(n(C)cc4C2)ccc3)C1 in smiles.smi (93/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(N(C)C)c1cc2/C(=C/CCN3CCN(C)CC3)/c3c(Sc2cc1)cccc3 in smiles.smi (94/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(CC)c1cc(C(=O)NC[C@@H]2N(CC)CCC2)c(OC)cc1 in smiles.smi (95/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(CC)c1c(N)cc(OC)c(C(=O)NC[C@H]2N(CC)CCC2)c1 in smiles.smi (96/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(C)N1C(=O)N(C(=O)N[C@@H](C(=O)N[C@@H]2C(=O)N3[C@@H](C(=O)O)C(C)(C)S[C@H]23)c2ccccc2)CC1 in smiles.smi (97/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(C)c1ccc(CC(=O)N2[C@@H](CN3C[C@@H](O)CC3)CN(C(=O)C)CC2)cc1 in smiles.smi (98/3605). Average speed: 0.15 s/mol.
Processing S(=O)(=O)(C)c1cc2N(CC[C@H]3N(C)CCCC3)c3c(Sc2cc1)cccc3 in smiles.smi (99/3605). Average speed: 0.15 s/mol.
Processing S([C@H]1C[C@@H](C(=O)N(C)C)NC1)C=1[C@@H](C)[C@@H]2[C@H]([C@@H](O)C)C(=O)N2C=1C(=O)O in smiles.smi (100/3605). Average speed: 0.15 s/mol.
Processing S([C@H](c1ccc(SCCCC)cc1)c1ccccc1)CCN(C)C in smiles.smi (101/3605). Average speed: 0.15 s/mol.
Processing S([C@@H]1CN2[N@](C1)CN=C2)C=1[C@@H](C)[C@H]2[C@H]([C@H](O)C)C(=O)N2C=1C(=O)O in smiles.smi (102/3605). Average speed: 0.15 s/mol.
Processing S([C@@H]1CN([C-]([N+H3])N)CC1)C1=C(C(=O)O)N2C(=O)[C@@H]([C@H](O)C)[C@H]2C1 in smiles.smi (103/3605). Average speed: 0.15 s/mol.
Processing S([C@@H]1C[C@H]([C@@H](O)CCNC)NC1)C=1[C@@H](C)[C@@H]2[C@H]([C@H](O)C)C(=O)N2C=1C(=O)O in smiles.smi (104/3605). Average speed: 0.15 s/mol.
Processing S(/C=C/C1=C(C(=O)O)N2C(=O)[C@@H](NC(=O)/C(=N/OC)/c3nc(N)sc3)[C@@H]2SC1)C=1N(CC=O)C(=O)C(=O)NN=1 in smiles.smi (105/3605). Average speed: 0.15 s/mol.
Processing S(/C=C/C#N)CC(=O)N[C@H]1C(=O)N2C(C(=O)O)=C(CSc3n(C)nnn3)CS[C@H]12 in smiles.smi (106/3605). Average speed: 0.15 s/mol.
Processing S(/C(=C(/N(C=O)Cc1c(N)nc(C)nc1)\C)/CCOP(=O)(O)O)C(=O)c1ccccc1 in smiles.smi (107/3605). Average speed: 0.15 s/mol.
Processing S(/C(=C(/N(C=O)Cc1c(N)nc(C)nc1)\C)/CCOC(=O)c1ccccc1)C(=O)c1ccccc1 in smiles.smi (108/3605). Average speed: 0.15 s/mol.
Processing S(/C(=C(/N(C=O)Cc1c(N)nc(C)nc1)\C)/CCOC(=O)C)C(=O)C in smiles.smi (109/3605). Average speed: 0.15 s/mol.
Processing P(C(=O)O)(=O)(O)O in smiles.smi (110/3605). Average speed: 0.15 s/mol.
Processing P(=O)(O)(O)[C@H]1[C@H](C)O1 in smiles.smi (111/3605). Average speed: 0.15 s/mol.
Processing OP(O)(=O)OCC(Cl)(Cl)Cl in smiles.smi (112/3605). Average speed: 0.15 s/mol.
Processing OP(O)(=O)CN1C(=O)NC(C1=O)(c2ccccc2)c3ccccc3 in smiles.smi (113/3605). Average speed: 0.15 s/mol.
Processing ONN in smiles.smi (114/3605). Average speed: 0.14 s/mol.
Processing OCCOCCN1CCN(CC1)C3=Nc2ccccc2Sc4ccccc34 in smiles.smi (116/3605). Average speed: 0.14 s/mol.
Processing OCCOCCOCCN1CCN(CC1)C(c2ccccc2)c3ccc(Cl)cc3 in smiles.smi (115/3605). Average speed: 0.14 s/mol.
Processing OCCOCCN1CCN(CC1)C(c2ccccc2)c3ccc(Cl)cc3 in smiles.smi (117/3605). Average speed: 0.14 s/mol.
Processing OCCOC4CCN(CCCN2c1ccccc1Sc3ccc(cc23)C(F)(F)F)CC4 in smiles.smi (118/3605). Average speed: 0.14 s/mol.
Processing OCCOC(=O)NCc1ccccc1 in smiles.smi (119/3605). Average speed: 0.14 s/mol.
Processing OCCN4CCN(CCCN2c1ccccc1Sc3ccc(Cl)cc23)CC4 in smiles.smi (120/3605). Average speed: 0.14 s/mol.
Processing OCCN4CCN(CCCN2c1ccccc1Sc3ccc(cc23)C(F)(F)F)CC4 in smiles.smi (121/3605). Average speed: 0.14 s/mol.
Processing OCCN4CCN(CCCN2c1ccccc1Sc3cc(Cl)cnc23)CC4 in smiles.smi (122/3605). Average speed: 0.14 s/mol.
Processing OCCN4CCN(CCCN2c1ccccc1C=Cc3ccccc23)CC4 in smiles.smi (123/3605). Average speed: 0.14 s/mol.
Processing OCCN4CCN(CCCN2c1cc(ccc1Sc3sccc23)C(F)(F)F)CC4 in smiles.smi (124/3605). Average speed: 0.14 s/mol.
Processing OCCN4CCN(CCCC2c1ccc(F)cc1Sc3ccc(cc23)C(F)(F)F)CC4 in smiles.smi (125/3605). Average speed: 0.14 s/mol.
Processing OCCN4CCN(CCC=C2c1ccccc1Sc3ccc(Cl)cc23)CC4 in smiles.smi (126/3605). Average speed: 0.14 s/mol.
Processing OCCN4CCN(CCC=C2c1ccccc1Sc3ccc(cc23)C(F)(F)F)CC4 in smiles.smi (127/3605). Average speed: 0.14 s/mol.
Processing OCCN4CCN(CCC=C2c1ccccc1COc3ccc(Cl)cc23)CC4 in smiles.smi (128/3605). Average speed: 0.14 s/mol.
Processing OCCN4CCN(CC/C=C2/C1=CC=CC=C1COC3=C/C=C(/[Cl])C=C23)CC4 in smiles.smi (129/3605). Average speed: 0.14 s/mol.
Processing OCCN4CCCN(CCCN2c1ccccc1Sc3ccc(cc23)C(F)(F)F)CC4 in smiles.smi (130/3605). Average speed: 0.14 s/mol.
Processing OCCN4CCCN(CCCN2c1ccccc1C=Cc3ccccc23)CC4 in smiles.smi (131/3605). Average speed: 0.14 s/mol.
Processing OCCN3C(=O)CN1CCOC1(c2ccccc2F)c4cc(Cl)ccc34 in smiles.smi (132/3605). Average speed: 0.14 s/mol.
Processing OCCN2C(=O)C(O)N=C(c1ccccc1F)c3cc(Cl)ccc23 in smiles.smi (133/3605). Average speed: 0.14 s/mol.
Processing OCCN1CCN(CC1)CCC(=O)N3c2ccccc2Sc4ccc(cc34)C(F)(F)F in smiles.smi (134/3605). Average speed: 0.14 s/mol.
Processing OCCN1CCN(CC1)C3CC(c2ccc(F)cc2)c4ccc(cc34)C(F)(F)F in smiles.smi (135/3605). Average speed: 0.14 s/mol.
Processing OCCN1CCN(CC1)[C@@]3([H])C[C@@]([H])(C2=C/C=C(/[F])C=C2)C4=CC=C(C=C34)C([F])([F])[F] in smiles.smi (136/3605). Average speed: 0.14 s/mol.
Processing OCCN(CCO)c4nc(N1CCCCC1)c3nc(nc(N2CCCCC2)c3n4)N(CCO)CCO in smiles.smi (137/3605). Average speed: 0.14 s/mol.
Processing OCCCN4CCN(CCCC2c1ccccc1Sc3ccc(Cl)cc23)CC4 in smiles.smi (138/3605). Average speed: 0.14 s/mol.
Processing OCCC4CCN(CCC=C2c1ccc(F)cc1Sc3ccc(cc23)C(F)(F)F)CC4 in smiles.smi (139/3605). Average speed: 0.14 s/mol.
Processing OCC1OC(CC1O)n2cnc3C(O)CNC=Nc23 in smiles.smi (141/3605). Average speed: 0.14 s/mol.
Processing OCC2OC(Oc1ccccc1CO)C(O)C(O)C2O in smiles.smi (140/3605). Average speed: 0.14 s/mol.
Processing OCc1ccccc1 in smiles.smi (142/3605). Average speed: 0.14 s/mol.
Processing OCC1CCC(O1)n2cnc3c(=O)[nH]cnc23 in smiles.smi (143/3605). Average speed: 0.14 s/mol.
Processing OCC1(CO)COC(OC1)C(Cl)(Cl)Cl in smiles.smi (144/3605). Average speed: 0.14 s/mol.
Processing OCC(O)C1OC(=O)C(=C1O)O in smiles.smi (147/3605). Average speed: 0.14 s/mol.
Processing OCC(O)CN2C(=O)CN=C(c1ccccc1F)c3cc(Cl)ccc23 in smiles.smi (145/3605). Average speed: 0.14 s/mol.
Processing OCC(O)C2OC1OC(OC1C2O)C(Cl)(Cl)Cl in smiles.smi (146/3605). Average speed: 0.14 s/mol.
Processing OCC(O)C(O)C(O)C(O)CO in smiles.smi (148/3605). Average speed: 0.13 s/mol.
Processing OCC(N)(CO)CO in smiles.smi (150/3605). Average speed: 0.13 s/mol.
Processing OCC(NC(=O)C(Cl)Cl)C(O)c1ccc(cc1)N(=O)=O in smiles.smi (149/3605). Average speed: 0.13 s/mol.
Processing OCC(C)(CO)C=1ON=C(N=1)C=4N=CN3C=2C=C/C=C(/[Cl])C=2C(=O)N(C)CC3=4 in smiles.smi (151/3605). Average speed: 0.13 s/mol.
Processing OCC(Br)(Br)Br in smiles.smi (152/3605). Average speed: 0.13 s/mol.
Processing Oc5ccc4CC2C1CCOCC1(CCN2CC3CC3)c4c5 in smiles.smi (153/3605). Average speed: 0.13 s/mol.
Processing Oc5ccc4CC2C1CCCCC1(CCN2CCc3ccccc3)c4c5 in smiles.smi (154/3605). Average speed: 0.13 s/mol.
Processing Oc5ccc4CC2C1CCCCC1(CCN2CC(=O)c3ccccc3)c4c5 in smiles.smi (155/3605). Average speed: 0.13 s/mol.
Processing Oc4ccc3CC2C1CCCCC1(CCN2CC=C)c3c4 in smiles.smi (157/3605). Average speed: 0.13 s/mol.
Processing Oc4cccc5CC2C1CCC(=O)CC1(CCN2CC3CC3)c45 in smiles.smi (156/3605). Average speed: 0.13 s/mol.
Processing Oc4ccc3CC1NCCC2(CCCCC12)c3c4 in smiles.smi (158/3605). Average speed: 0.13 s/mol.
Processing Oc4ccc3CC1N(CCC2(CCCCC12O)c3c4)CC5CCC5 in smiles.smi (159/3605). Average speed: 0.13 s/mol.
Processing Oc4ccc3CC1N(CCC2(CCCCC12O)c3c4)CC5CC5 in smiles.smi (160/3605). Average speed: 0.13 s/mol.
Processing Oc4ccc(CCNC(=O)C23CC1CC(CC(C1)C2)C3)cc4O in smiles.smi (162/3605). Average speed: 0.13 s/mol.
Processing Oc4ccc3[nH]cc(CCCCN1CCC(=CC1)c2ccccc2)c3c4 in smiles.smi (161/3605). Average speed: 0.13 s/mol.
Processing OC4=C(C1CCC(CC1)c2ccc(Cl)cc2)C(=O)c3ccccc3C4=O in smiles.smi (163/3605). Average speed: 0.13 s/mol.
Processing OC4(CCN(CCCN2c1ccccc1Sc3ccc(Cl)cc23)CC4)C5CCOC5=O in smiles.smi (164/3605). Average speed: 0.13 s/mol.
Processing OC3N=C(c1ccccc1Cl)c2nc(Cl)ccc2NC3=O in smiles.smi (165/3605). Average speed: 0.13 s/mol.
Processing OC3N=C(c1ccccc1Cl)c2cc(Cl)ccc2NC3=O in smiles.smi (166/3605). Average speed: 0.13 s/mol.
Processing OC3N=C(c1ccccc1)c2cc(Cl)ccc2NC3=O in smiles.smi (167/3605). Average speed: 0.13 s/mol.

In [5]:
pip install h5py

Requirement already satisfied: h5py in /opt/anaconda3/lib/python3.11/site-packages (3.11.0)
Requirement already satisfied: numpy>=1.17.3 in /opt/anaconda3/lib/python3.11/site-packages (from h5py) (1.26.4)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import h5py
with h5py.File("DeePredmodel.h5", "r") as f:
    def printname(name):
        print(name)
    f.visit(printname)

model_weights
model_weights/batch_normalization_17
model_weights/batch_normalization_17/batch_normalization_17
model_weights/batch_normalization_17/batch_normalization_17/beta:0
model_weights/batch_normalization_17/batch_normalization_17/gamma:0
model_weights/batch_normalization_17/batch_normalization_17/moving_mean:0
model_weights/batch_normalization_17/batch_normalization_17/moving_variance:0
model_weights/dense_26
model_weights/dense_26/dense_26
model_weights/dense_26/dense_26/bias:0
model_weights/dense_26/dense_26/kernel:0
model_weights/dense_27
model_weights/dense_27/dense_27
model_weights/dense_27/dense_27/bias:0
model_weights/dense_27/dense_27/kernel:0
model_weights/dropout_26
model_weights/dropout_27

In [11]:
import pandas as pd

In [12]:
DeePred_BBB_df = pd.DataFrame([["folic acid", "CHEMBL1622"],
                              ["paracetamol", "CHEMBL112"]], columns = ["Name", "ChEMBL"])

In [14]:
DeePred_BBB_df.to_csv("PaDEL_features.csv")

In [23]:
df = pd.read_csv("smiles.smi", header=None, names = ['SMILES'])

In [21]:
df.iloc[0, 0]

'[F]/C2=C/C=1ON=C(C=1C=C2)[C@@]5([H])CCN(CCC=4C(=O)N3CCC[C@@](O)([H])C3=NC=4C)CC5 test'

In [132]:
df = pd.read_excel('Table 1.xlsx')
df

,SL,Compounds,PID,BBB-Class,References,Unnamed: 5,Unnamed: 6
0,1,SCC(=O)[C@@]1(O)[C@@]2(C)[C@H]([C@H]3[C@H]([C@...,NaN,1,Roy et al. ACS Omega. 2019; 4(16):16774-16780....,NaN,BBB-Class 1: Permeable
1,2,s1cc(nc1[NH]=C(N)N)C,6928896,1,Zhao et al. J Chem Inf Model. 2007;47(1):170–...,NaN,BBB-Class 0: Non-permeable
2,3,s1cc(CSCCNC(NC)=[NH]C#N)nc1[NH]=C(N)N,NaN,1,Zhao et al. J Chem Inf Model. 2007;47(1):170–...,NaN,NaN
3,4,s1c(ncc1)CCN,87653,1,Zhao et al. J Chem Inf Model. 2007;47(1):170–...,NaN,NaN
4,5,S=P(N1CC1)(N2CC2)N3CC3,5453,1,Zhao et al. J Chem Inf Model. 2007;47(1):170–...,NaN,NaN
...,...,...,...,...,...,...,...
3600,3601,[C@H]1(c2ccccc2)[N@]2[C@@H](NC1)NCC2,NaN,1,Roy et al. ACS Omega. 2019; 4(16):16774-16780....,NaN,NaN
3601,3602,[C@H]1([C@@H]2NCCCC2)OC(c2ccccc2)(c2ccccc2)OC1,14208378,1,Roy et al. ACS Omega. 2019; 4(16):16774-16780....,NaN,NaN
3602,3603,[C@H](CCC)(Cc1ccccc1)N1CCCC1,54153082,1,Roy et al. ACS Omega. 2019; 4(16):16774-16780....,NaN,NaN
3603,3604,[C@H](CCC)(CC)C,13800357,1,Roy et al. ACS Omega. 2019; 4(16):16774-16780....,NaN,NaN
3604,3605,[C@H](C)(n1c(C)ncc1)c1ccccc1,76960079,1,Roy et al. ACS Omega. 2019; 4(16):16774-16780....,NaN,NaN

In [133]:
smi_column = df['Compounds']
smi_column

0       SCC(=O)[C@@]1(O)[C@@]2(C)[C@H]([C@H]3[C@H]([C@...
1                                    s1cc(nc1[NH]=C(N)N)C
2                   s1cc(CSCCNC(NC)=[NH]C#N)nc1[NH]=C(N)N
3                                            s1c(ncc1)CCN
4                                  S=P(N1CC1)(N2CC2)N3CC3
                              ...
3600                 [C@H]1(c2ccccc2)[N@]2[C@@H](NC1)NCC2
3601       [C@H]1([C@@H]2NCCCC2)OC(c2ccccc2)(c2ccccc2)OC1
3602                         [C@H](CCC)(Cc1ccccc1)N1CCCC1
3603                                      [C@H](CCC)(CC)C
3604                         [C@H](C)(n1c(C)ncc1)c1ccccc1
Name: Compounds, Length: 3605, dtype: object

In [27]:
smi_column

0       SCC(=O)[C@@]1(O)[C@@]2(C)[C@H]([C@H]3[C@H]([C@...
1                                    s1cc(nc1[NH]=C(N)N)C
2                   s1cc(CSCCNC(NC)=[NH]C#N)nc1[NH]=C(N)N
3                                            s1c(ncc1)CCN
4                                  S=P(N1CC1)(N2CC2)N3CC3
                              ...
3600                 [C@H]1(c2ccccc2)[N@]2[C@@H](NC1)NCC2
3601       [C@H]1([C@@H]2NCCCC2)OC(c2ccccc2)(c2ccccc2)OC1
3602                         [C@H](CCC)(Cc1ccccc1)N1CCCC1
3603                                      [C@H](CCC)(CC)C
3604                         [C@H](C)(n1c(C)ncc1)c1ccccc1
Name: Compounds, Length: 3605, dtype: object

In [165]:
run_prediction("smiles.smi")

NameError: name 'run_prediction' is not defined

In [28]:
smi_df = pd.DataFrame(smi_column)

In [158]:
smi_df

                                              Compounds
0     SCC(=O)[C@@]1(O)[C@@]2(C)[C@H]([C@H]3[C@H]([C@...
1                                  s1cc(nc1[NH]=C(N)N)C
2                 s1cc(CSCCNC(NC)=[NH]C#N)nc1[NH]=C(N)N
3                                          s1c(ncc1)CCN
4                                S=P(N1CC1)(N2CC2)N3CC3
...                                                 ...
3600               [C@H]1(c2ccccc2)[N@]2[C@@H](NC1)NCC2
3601     [C@H]1([C@@H]2NCCCC2)OC(c2ccccc2)(c2ccccc2)OC1
3602                       [C@H](CCC)(Cc1ccccc1)N1CCCC1
3603                                    [C@H](CCC)(CC)C
3604                       [C@H](C)(n1c(C)ncc1)c1ccccc1

[3605 rows x 1 columns]

In [159]:
new_df = smi_df + ' ' + smi_df

In [162]:
new_df.iloc[0][0]

/var/folders/16/gzssnc2x4qz5n4rkpvt7tsjh0000gn/T/ipykernel_60930/3781837699.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  new_df.iloc[0][0]

'SCC(=O)[C@@]1(O)[C@@]2(C)[C@H]([C@H]3[C@H]([C@H](O)C2)[C@]2(C)C(=CC(=O)CC2)CC3)CC1 SCC(=O)[C@@]1(O)[C@@]2(C)[C@H]([C@H]3[C@H]([C@H](O)C2)[C@]2(C)C(=CC(=O)CC2)CC3)CC1'

In [144]:
# compound_with_name_test = smi_df.iloc[6] + ' S=C1O[C@@H](COc2ccccc2)CCN1'

In [145]:
compound_with_name_test

Compounds    S=C1O[C@@H](COc2ccccc2)CCN1 S=C1O[C@@H](COc2cc...
Name: 6, dtype: object

In [2]:
new_df = 'C(C1C(NC(Cc2c[nH]cn2)C(NC(C(NC(C(=O)NC(C(NC(C(NC(C(N1)=O)C(CC)C)=O)CCCN)=O)CCCCNC(C(NC(C(NC(C(NC(C1N=C(C(C(CC)C)N)SC1)=O)CC(C)C)=O)CCC(O)=O)=O)C(CC)C)=O)CC(N)=O)=O)CC(O)=O)=O)=O)c1ccccc1' + " " + 'C(C1C(NC(Cc2c[nH]cn2)C(NC(C(NC(C(=O)NC(C(NC(C(NC(C(N1)=O)C(CC)C)=O)CCCN)=O)CCCCNC(C(NC(C(NC(C(NC(C1N=C(C(C(CC)C)N)SC1)=O)CC(C)C)=O)CCC(O)=O)=O)C(CC)C)=O)CC(N)=O)=O)CC(O)=O)=O)=O)c1ccccc1'

In [3]:
new_df.to_csv("smiles.smi", header=None, index = False)

AttributeError: 'str' object has no attribute 'to_csv'

In [131]:
pd.read_csv("/Users/alexwang/Documents/GitHub/DeePred-BBB/smiles.smi") #, header=None, names = ['SMILES'])

Empty DataFrame
Columns: [S=C1NC(=O)C([C@@H](CCC)C)(CC=C)C(=O)N1]
Index: []

In [11]:
pd.read_csv("/Users/alexwang/Desktop/smiles.smi") #, header=None, names = ['SMILES'])

Empty DataFrame
Columns: [[F]/C2=C/C=1ON=C(C=1C=C2)[C@@]5([H])CCN(CCC=4C(=O)N3CCC[C@@](O)([H])C3=NC=4C)CC5 test]
Index: []

In [92]:
df_temp = pd.DataFrame({"name": [1, 2]})
df_temp

   name
0     1
1     2

In [101]:
temp_array = np.array([[[1., 0.]],
                       [[0., 1.]],
                      [[1., 0.]]])

In [102]:
temp_array.shape

(3, 1, 2)

In [110]:
temp_array[:, :, 0]

array([[1.],
       [0.],
       [1.]])

In [112]:
import numpy as np
df_temp['Predicted_class'] = np.array([[1.],
                                       [0.],])
# df_temp.to_csv("df_temp.csv")

In [113]:
df_temp

   name  Predicted_class
0     1              1.0
1     2              0.0